config/routes.rb
NgdaleRails4::Application.routes.draw do

  root :to => "pages#home"
  devise_for :users, :controllers => { :sessions => "users/sessions" }

  resources :sermons, :only => [:index, :show]
  namespace :admin do
    root :to => "dashboard#home"
    resources :sermons
    resources :blog_posts
    resources :pages
    resources :updates do
      collection do
        get :phone_call
      end
    end
  end

  namespace :members do
    root :to => "dashboard#home"
  end

  get '/:slug' => "pages#show"
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "500x360>", :small => "250x180>" }
  def name
    read_attribute("name") || ""
  end
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  has_attached_file :audio
end

app/models/update.rb
class Update < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def make_admin!
    self.update_attribute(:admin, true)
  end

  def admin?
    admin
  end

  def name
    email
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def home
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      redirect_to admin_pages_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy!
    redirect_to admin_pages_path
  end

  protected
  def page_params
    params.require(:page).permit(:title, :name, :body, :image)
  end
end

app/controllers/admin/sermons_controller.rb
class Admin::SermonsController < Admin::ApplicationController
  before_action :set_sermon, only: [:show, :edit, :update, :destroy]

  # GET /sermons
  # GET /sermons.json
  def index
    @sermons = Sermon.order(:date => :desc).all
  end

  # GET /sermons/1
  # GET /sermons/1.json
  def show
  end

  # GET /sermons/new
  def new
    @sermon = Sermon.new
  end

  # GET /sermons/1/edit
  def edit
  end

  # POST /sermons
  # POST /sermons.json
  def create
    @sermon = Sermon.new(sermon_params)

    respond_to do |format|
      if @sermon.save
        format.html { redirect_to admin_sermon_path(@sermon), notice: 'Sermon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sermon }
      else
        format.html { render action: 'new' }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sermons/1
  # PATCH/PUT /sermons/1.json
  def update
    respond_to do |format|
      if @sermon.update(sermon_params)
        format.html { redirect_to admin_sermon_path(@sermon), notice: 'Sermon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sermons/1
  # DELETE /sermons/1.json
  def destroy
    @sermon.destroy
    respond_to do |format|
      format.html { redirect_to admin_sermons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sermon
      @sermon = Sermon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sermon_params
      params.require(:sermon).permit(:title, :body, :date, :summary, :audio, :preacher)
    end
end

app/controllers/admin/updates_controller.rb
class Admin::UpdatesController < Admin::ApplicationController

  skip_before_filter :authenticate_user!, :only => [:phone_call]
  skip_before_filter :authenticate_admin!, :only => [:phone_call]

  def index
    @updates = Update.all
  end

  def phone_call
    response = Twilio::TwiML::Response.new do |r|
      if Update.count == 0
        r.Say 'There are no updates today! Thanks for calling!', :voice => 'woman'
      else
        Update.all.each do |update|
          r.Say update.summary, :voice => 'woman'
        end
      end
    end
    render text: response.text
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.where(:slug => params[:slug]).first
    raise ActionController::RoutingError.new('Not Found') unless @page
  end
end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController

  def index
    @sermons = Sermon.order(:date => :desc).page(params[:page])
  end

  def show
    @sermon = Sermon.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "members"
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/members/dashboard_helper.rb
module Members::DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/admin/pages/_form.html.haml
= form_for @page, url: admin_page_path(@page), html: { :multipart => true } do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :body
    = f.text_area :body, class: 'wysihtml5', size: "30x20"
  .actions
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', admin_page_path(@page)
\|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 Listing Pages

.navbar
  .navbar-inner
    %ul.nav
      %li
        = link_to 'New Page', new_admin_page_path

%table.table.table-bordered
  %tr
    %th Title
    %th Slug
    %th

  - @pages.each do |page|
    %tr
      %td= page.title
      %td= page.slug
      %td 
        = link_to 'Edit', edit_admin_page_path(page), class: 'btn'
        = link_to 'Destroy', admin_page_path(page), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn'

app/views/admin/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", "data-turbolinks-track" => true
    = stylesheet_link_tag "admin/admin"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{href: "/admin"}
            %strong Admin Panel
          %ul.nav
            %li.divider-vertical
            %li{class: current_page?(admin_root_path) ? "active" : ""}
              = link_to "Home", admin_root_path
            %li{class: current_page?(admin_pages_path) ? "active" : ""}
              = link_to "Pages", admin_pages_path
            %li{ class: current_page?(admin_sermons_path) ? "active" : "" }
              = link_to "Sermons", admin_sermons_path
            %li{ class: current_page?(admin_blog_posts_path) ? "active" : "" }
              = link_to "Blog Posts", admin_blog_posts_path
          %ul.nav.pull-right
            %li
              = link_to "Logout", destroy_user_session_path, :method => :delete
    .container
      = yield

  :javascript
    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Home
    %meta{:charset => "utf-8"}/
    = stylesheet_link_tag    "reset", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "style", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "application", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "cufon-yui.js", "data-turbolinks-track" => true
    = javascript_include_tag "cufon-replace.js", "data-turbolinks-track" => true
    = javascript_include_tag "Vegur_700.font.js", "data-turbolinks-track" => true
    = javascript_include_tag "Vegur_400.font.js", "data-turbolinks-track" => true
    = javascript_include_tag "Vegur_300.font.js", "data-turbolinks-track" => true
    = javascript_include_tag "jquery.easing.1.3.js", "data-turbolinks-track" => true
    = javascript_include_tag "tms-0.3.js", "data-turbolinks-track" => true
    = javascript_include_tag "tms_presets.js", "data-turbolinks-track" => true
    = javascript_include_tag "backgroundPosition.js", "data-turbolinks-track" => true
    = csrf_meta_tags
    /[if lt IE 9]
      <script type="text/javascript" src="js/html5.js"></script>
      <style type="text/css">
      \.box1 figure {behavior:url(js/PIE.htc)}
      </style>
    /[if lt IE 7]
      <div style='clear:both;text-align:center;position:relative'>
      <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/images/upgrade.jpg" border="0" alt="" /></a>
      </div>
  %body#page1
    .body1
      .main
        %header
          .wrapper
            %h1
              #logo{:href => "/"}
                North Gardendale
              %br/
              %br/
              %br/
              #logo_small church of Christ
            %nav
              %ul#top_nav
                %li
                  %a{:href => "/"}
                    %img{:alt => "", :src => "/images/top_icon1.gif"}/
                %li
                  %a{:href => "#"}
                    %img{:alt => "", :src => "/images/top_icon2.gif"}/
                %li.end
                  %a{:href => "/contact"}
                    %img{:alt => "", :src => "/images/top_icon3.gif"}/
            %nav
              %ul#menu
                %li{:id => request.path == "/" ? "menu_active" : ""}
                  %a{:href => "/"} Home
                %li{:id => request.path == "/about" ? "menu_active" : ""}
                  %a{:href => "/about"} About Us
                %li{:id => request.path == "/location" ? "menu_active" : ""}
                  %a{:href => "/location"} Location
                %li{:id => request.path == "/services" ? "menu_active" : ""}
                  %a{:href => "/services"} Services
                %li{:id => request.path == "/members" ? "menu_active" : ""}
                  %a{:href => "/members"} Members
                %li{:id => request.path == "/contact" ? "menu_active" : ""}
                  %a{:href => "/contact"} Contact Us
        .ic
        = yield
        .wrapper
          %ul#icons
            %li
              %a.normaltip{:href => "https://www.facebook.com/pages/North-Gardendale-church-of-Christ/246315291774", :title => "Facebook"}
                %img{:alt => "", :src => "/images/icon1.gif"}/
        .wrapper
          %nav
            %ul#footer_menu
              %li.active
                %a{:href => "/"} Home
              %li
                %a{:href => "/about"} About Us
              %li
                %a{:href => "/location"} Location
              %li
                %a{:href => "/services"} Services
              %li
                %a{:href => "/admin"} Admin
              %li.end
                %a{:href => "/contact"} Contact Us
          .tel
            %span> +1 205 
            &nbsp;
            631-8415
        :javascript
          $(document).ready(function() {
            Cufon.now();
            tabs.init()
          }

app/views/layouts/members.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css", "data-turbolinks-track" => true
    = stylesheet_link_tag "members/members"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{href: root_url}
            %strong Members Panel
          -if current_user
            %ul.nav
              %li{class: current_page?(members_root_path) ? "active" : ""}
                = link_to "Home", members_root_path
              - if current_user && current_user.admin?
                %li
                  = link_to "Admin Panel", admin_root_path
              %li
                = link_to "Member Directory", "#"
            %ul.nav.pull-right
              %li
                = link_to "Logout", destroy_user_session_path, :method => :delete
    .container
      = yield

app/views/pages/_sermons.html.haml
- Sermon.limit(3).order("date DESC").all.each_with_index do |sermon, index|
  %section{class: "col1 #{index > 0 ? "pad_left1": nil}"}
    %h4.color2
      %span>="#{sermon.date.strftime("%B ")} #{sermon.date.day.ordinalize}"
      = sermon.date.year
    %p.pad_bot2
      %strong= sermon.title
      %br/
      %strong= sermon.preacher
    %p= sermon.summary 
    = link_to "Listen Now", sermon, class: "button2"

app/views/pages/home.html.haml
.slider
  %ul.items
    %li
      %img{:alt => "", :src => "images/img1.jpg"}/
      -#
        .banner
          .wrapper
            %span
              “We're
              the North Gardendale
          .wrapper
            %strong
              church
              of Christ”
    %li
      %img{:alt => "", :src => "images/img2.jpg"}/
      -#
        .banner
          .wrapper
            %span “In a building
          .wrapper
            %strong a CHURCH building”
    %li
      %img{:alt => "", :src => "images/img3.jpg"}/
      -#
        .banner
          .wrapper
            %span “Twice on Sunday
          .wrapper
            %strong and once on Wednesday”
  %ul.pagination
    %li#banner1
      %a{:href => "#"}
        About Us
        %span Who We Are
    %li#banner2
      %a{:href => "#"}
        Location
        %span Where we meet
    %li#banner3
      %a{:href => "#"}
        Services
        %span When we meet
.ic
/ / header
/ content
%article#content
.wrapper
  .box1
    .line1
      .line2.wrapper
        %section.col1
          %h2
            %strong> W
            hat
            %span To Expect
          .pad_bot1
            %figure
              %img{:alt => "", :src => "images/page1_img1.jpg"}/
          We hope you'll visit our services sometime soon
          %br
          %br
          %a.button1{:href => "/services"} Read More
        %section.col1.pad_left1
          %h2.color2
            %strong> B
            ible
            %span Studies
          .pad_bot1
            %figure
              %img{:alt => "", :src => "images/page1_img2.jpg"}/
          We have bible classes from ages 2 to adults
          %br
          %br
          %a.button1.color2{:href => "/bible_studies"} Read More
        %section.col1.pad_left1
          %h2.color3
            %strong> R
            eading
            %span Plans
          .pad_bot1
            %figure
              %img{:alt => "", :src => "images/page1_img3.jpg"}/
          Links to Bible lessons, sermons, bulletins and helpful websites
          %br
          %br
          %a.button1.color3{:href => "/reading_plans"} Read More
.wrapper
  %h3 Daily Verse
  %p.quot
    For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.
    John 3:16
    %img{:alt => "", :src => "images/quot2.png"}/

.wrapper
  .box2
    .line1
      .line2.wrapper
        = render "sermons"
:javascript
  $(document).ready(function(){
    $('.slider')._TMS({
      preset:'zabor',
      easing:'easeOutQuad',
      duration:800,
      pagination:true,
      banners:true,
      waitBannerAnimation:false,
      slideshow:6000,
      bannerShow:function(banner){
        banner
          .css({right:'-700px'})
          .stop()
          .animate({right:'0'},600, 'easeOutExpo')
      },
      bannerHide:function(banner){
        banner
          .stop()
          .animate({right:'-700'},600,'easeOutExpo')
      }
      })
      $('.pagination li').hover(function(){
        if (!$(this).hasClass('current')) {
          $(this).find('a').stop().animate({backgroundPosition:'0 0'},600,'easeOutExpo', function(){$(this).parent().css({backgroundPosition:'-20px 0'})});
        }
      },function(){
        if (!$(this).hasClass('current')) {
          $(this).css({backgroundPosition:'0 0'}).find('a').stop().animate({backgroundPosition:'-250px 0'},600,'easeOutExpo');
        }
    })
  })

app/views/pages/show.html.haml
%article#content.tabs
  .wrapper
    .box1
      .wrapper
        %section.col4
          %h2
            %strong>= @page.name[0]
            =@page.name[1..-1]
          %div
            %figure.left.marg_right1
              %img#image{:style => "width: 250px; height: 180px;", :alt => "", :src => @page.image.url(:small)}/
            #body=@page.body.try(:html_safe)