config/routes.rb
NgdaleRails4::Application.routes.draw do

  root :to => "pages#home"
  devise_for :users, :controllers => { :sessions => "users/sessions" }

  resources :sermons, :only => [:index, :show]
  namespace :admin do
    root :to => "dashboard#home"
    resources :sermons
    resources :blog_posts
    resources :pages
    resources :updates do
      collection do
        get :phone_call
      end
    end
  end

  namespace :members do
    root :to => "dashboard#home"
  end

  get '/:slug' => "pages#show"
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "500x360>", :small => "250x180>" }
  def name
    read_attribute("name") || ""
  end
end

app/models/sermon.rb
class Sermon < ActiveRecord::Base
  has_attached_file :audio
end

app/models/update.rb
class Update < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def make_admin!
    self.update_attribute(:admin, true)
  end

  def admin?
    admin
  end

  def name
    email
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout "admin"

  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def authenticate_admin!
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < Admin::ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to admin_blog_post_path(@blog_post), notice: 'Blog post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to admin_blog_post_path(@blog_post), notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_blog_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body, :user_id)
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def home
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      redirect_to admin_pages_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy!
    redirect_to admin_pages_path
  end

  protected
  def page_params
    params.require(:page).permit(:title, :name, :body, :image)
  end
end

app/controllers/admin/sermons_controller.rb
class Admin::SermonsController < Admin::ApplicationController
  before_action :set_sermon, only: [:show, :edit, :update, :destroy]

  # GET /sermons
  # GET /sermons.json
  def index
    @sermons = Sermon.order(:date => :desc).all
  end

  # GET /sermons/1
  # GET /sermons/1.json
  def show
  end

  # GET /sermons/new
  def new
    @sermon = Sermon.new
  end

  # GET /sermons/1/edit
  def edit
  end

  # POST /sermons
  # POST /sermons.json
  def create
    @sermon = Sermon.new(sermon_params)

    respond_to do |format|
      if @sermon.save
        format.html { redirect_to admin_sermon_path(@sermon), notice: 'Sermon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sermon }
      else
        format.html { render action: 'new' }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sermons/1
  # PATCH/PUT /sermons/1.json
  def update
    respond_to do |format|
      if @sermon.update(sermon_params)
        format.html { redirect_to admin_sermon_path(@sermon), notice: 'Sermon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sermon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sermons/1
  # DELETE /sermons/1.json
  def destroy
    @sermon.destroy
    respond_to do |format|
      format.html { redirect_to admin_sermons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sermon
      @sermon = Sermon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sermon_params
      params.require(:sermon).permit(:title, :body, :date, :summary, :audio, :preacher)
    end
end

app/controllers/admin/updates_controller.rb
class Admin::UpdatesController < Admin::ApplicationController

  skip_before_filter :authenticate_user!, :only => [:phone_call]
  skip_before_filter :authenticate_admin!, :only => [:phone_call]

  def index
    @updates = Update.all
  end

  def phone_call
    response = Twilio::TwiML::Response.new do |r|
      if Update.count == 0
        r.Say 'There are no updates today! Thanks for calling!', :voice => 'woman'
      else
        Update.all.each do |update|
          r.Say update.summary, :voice => 'woman'
        end
      end
    end
    render text: response.text
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members/application_controller.rb
class Members::ApplicationController < ApplicationController
  layout "members"

  before_filter :authenticate_user!
end

app/controllers/members/dashboard_controller.rb
class Members::DashboardController < Members::ApplicationController

  def home
    @blog_posts = BlogPost.limit(5).page params[:page]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.where(:slug => params[:slug]).first
    raise ActionController::RoutingError.new('Not Found') unless @page
  end
end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController

  def index
    @sermons = Sermon.order(:date => :desc).page(params[:page])
  end

  def show
    @sermon = Sermon.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "members"
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/members/dashboard_helper.rb
module Members::DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/views/admin/sermons/_form.html.haml
= form_for @sermon, url: admin_sermon_path(@sermon) do |f|
  - if @sermon.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sermon.errors.count, "error")} prohibited this sermon from being saved:"
      %ul
        - @sermon.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :preacher
    = f.text_field :preacher
  .field
    = f.label :body
    = f.text_area :body, class: 'wysihtml5', size: "30x20"
  .field
    = f.label :audio
    = f.file_field :audio
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :summary
    = f.text_area :summary
  .actions
    = f.submit 'Save'

app/views/admin/sermons/edit.html.haml
%h1 Editing sermon

= render 'form'

= link_to 'Show', admin_sermon_path(@sermon)
\|
= link_to 'Back', admin_sermons_path

app/views/admin/sermons/index.html.haml
%h1 Listing sermons

.navbar
  .navbar-inner
    %ul.nav
      %li.divider-vertical
      %li
        = link_to 'New Sermon', new_admin_sermon_path
      %li.divider-vertical

%table.table.table-bordered
  %tr
    %th Date
    %th Title
    %th Summary
    %th

  - @sermons.each do |sermon|
    %tr
      %td= sermon.date
      %td= sermon.title
      %td= sermon.summary
      %td 
        = link_to 'Show', admin_sermon_path(sermon), class: 'btn'
        = link_to 'Edit', edit_admin_sermon_path(sermon), class: 'btn'
        = link_to 'Destroy', admin_sermon_path(sermon), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn'

app/views/admin/sermons/new.html.haml
%h1 New sermon

= render 'form'

= link_to 'Back', admin_sermons_path

app/views/admin/sermons/show.html.haml
%p#notice= notice

.navbar
  .navbar-inner
    %ul.nav
      %li.divider-vertical
      %li
        = link_to 'Edit', edit_admin_sermon_path(@sermon)
      %li.divider-vertical
      %li
        = link_to 'Back', admin_sermons_path
      %li.divider-vertical

%h1= "#{@sermon.title} - #{@sermon.date}"
%hr
= @sermon.body.html_safe

app/views/members/dashboard/home.html.haml
- @blog_posts.each do |blog_post|
  .navbar
    .navbar-inner
      .brand= blog_post.title
      .pull-left.navbar-text= blog_post.user.name
      .pull-right.navbar-text= blog_post.created_at.strftime("%m-%d-%y")
  .well= blog_post.body.html_safe
  %br
= paginate @blog_posts

app/views/sermons/index.html.haml
%article#content.tabs
  .wrapper
    .box1
      .wrapper
        %section.col4
          %h2
            %strong> S
            ermons
          %div
            #body
              %table
                %tr
                  %th Date
                  %th Title
                  %th Preacher
                - @sermons.each do |sermon|
                  %tr
                    %td= sermon.date
                    %td= link_to sermon.title, sermon
                    %td= sermon.preacher
              = paginate @sermons

app/views/sermons/show.html.haml
%article#content.tabs
  .wrapper
    .box1
      .wrapper
        %section.col4
          %h2
            %strong>= @sermon.title[0]
            =@sermon.title[1..-1]
          %div
            %figure.left.marg_right1
            %audio{:controls => ""}
              %source{:src => @sermon.audio.to_s, :type => "audio/mpeg"}
            %br/
            #body= @sermon.body.try(:html_safe)
            %br/
            = link_to "Download", @sermon.audio.to_s, class: "button2"